In [8]:
my_list = [1,2,3]

In [9]:
import numpy as np

In [10]:
 np.array(my_list)

array([1, 2, 3])

In [11]:
arr = np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [14]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
 np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.21137663, 0.23778185, 0.56850806, 0.7785031 , 0.34835476])

In [24]:
np.random.randint(1,100,10)

array([ 1, 52, 95, 35, 67,  3, 86, 30, 94, 97], dtype=int32)